# Default values for web-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: abhishekf5/go-web-app
  pullPolicy: IfNotPresent
  tag: "10016307834"  # Overrides the image tag whose default is the chart appVersion.

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
